# Generated by Django 4.0.4 on 2022-05-22 20:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBase',
            fields=[
                ('courseName', models.CharField(max_length=55)),
                ('courseCode', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('courseDays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('courseDepartment', models.CharField(max_length=55)),
                ('courseHours', models.IntegerField()),
                ('courseHall', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBase',
            fields=[
                ('studentName', models.CharField(max_length=55)),
                ('studentId', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('studentDay', models.IntegerField()),
                ('studentMonth', models.IntegerField()),
                ('studentYear', models.IntegerField()),
                ('studentUniversity', models.CharField(max_length=55)),
                ('studentDepartment', models.CharField(max_length=55)),
                ('studentCourse1', models.CharField(max_length=55)),
                ('studentCourse2', models.CharField(max_length=55)),
                ('studentCourse3', models.CharField(max_length=55)),
                ('studentActive', models.BooleanField()),
                ('studentStatus', models.BooleanField()),
            ],
        ),
    ]
