# Generated by Django 4.0.4 on 2022-05-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_coursebase_coursedays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebase',
            name='courseName',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
