# Generated by Django 4.0.4 on 2022-05-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_coursebase_coursename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursebase',
            old_name='courseDays',
            new_name='course_days',
        ),
    ]
