# Generated by Django 4.0.4 on 2022-05-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_student_active_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
