# Generated by Django 4.0.4 on 2022-05-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_student_active_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.CharField(choices=[(0, 'Inactive'), (1, 'Active')], max_length=1),
        ),
    ]
