# Generated by Django 4.0.4 on 2022-05-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_course_student_delete_coursebase_delete_studentbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
