# Generated by Django 4.0.4 on 2022-05-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_student_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course3',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='pages.course'),
        ),
    ]
