# Generated by Django 4.0.4 on 2022-05-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_student_course1_remove_student_course2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], max_length=1),
        ),
    ]
