# Generated by Django 4.0.4 on 2022-05-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_course_department_alter_student_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('General', '0'), ('AI', '1'), ('CS', '2'), ('IS', '3'), ('IT', '4'), ('DS', '5')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.CharField(choices=[('Active', '1'), ('Inactive', '0')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('General', '0'), ('AI', '1'), ('CS', '2'), ('IS', '3'), ('IT', '4'), ('DS', '5')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Male', '1'), ('Female', '0')], default='1', max_length=10),
        ),
    ]
