# Generated by Django 4.0.4 on 2022-05-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('General', 'General'), ('AI', 'AI'), ('AI', 'AI'), ('IS', 'IS'), ('IT', 'IT'), ('DS', 'DS')], default='General', max_length=10),
        ),
    ]
