# Generated by Django 4.0.4 on 2022-05-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_student_active_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('General', 'General'), ('AI', 'AI'), ('CS', 'CS'), ('IS', 'IS'), ('IT', 'IT'), ('DS', 'DS')], default='General', max_length=10),
        ),
    ]
