# Generated by Django 4.0.4 on 2022-05-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
